#!/usr/bin/env python3
"""Rasterize the cburnett chess piece SVGs into 1-bit shape and ink masks.

Usage: gen_chess_pieces.py <svg dir> <out header> [size]
Needs rsvg-convert on PATH and Pillow. Each piece becomes two MSB-first
bitmaps of size*size bits: `shape` marks opaque pixels, `ink` marks black
pixels. The renderer paints white where shape is set and ink is clear.
"""
import os
import subprocess
import sys

from PIL import Image

PIECES = ["wP", "wN", "wB", "wR", "wQ", "wK", "bP", "bN", "bB", "bR", "bQ", "bK"]


def rasterize(svg, size):
    png = svg[:-4] + f"_{size}.png"
    subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size), "-o", png, svg], check=True)
    return Image.open(png).convert("RGBA")


def masks(img, size):
    shape = bytearray((size * size + 7) // 8)
    ink = bytearray((size * size + 7) // 8)
    px = img.load()
    for y in range(size):
        for x in range(size):
            r, g, b, a = px[x, y]
            i = y * size + x
            if a > 110:
                shape[i >> 3] |= 0x80 >> (i & 7)
                lum = (r * 299 + g * 587 + b * 114) // 1000
                # Blend semi-transparent edge pixels toward the paper color.
                lum = (lum * a + 255 * (255 - a)) // 255
                if lum < 140:
                    ink[i >> 3] |= 0x80 >> (i & 7)
    return shape, ink


def fmt(name, data):
    rows = []
    for i in range(0, len(data), 20):
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in data[i : i + 20]) + ",")
    return f"constexpr uint8_t {name}[{len(data)}] = {{\n" + "\n".join(rows) + "\n};\n"


def main():
    svg_dir, out, size = sys.argv[1], sys.argv[2], int(sys.argv[3]) if len(sys.argv) > 3 else 60
    parts = [
        "#pragma once\n",
        "// Generated by scripts/gen_chess_pieces.py from the Lichess cburnett piece set\n",
        "// (Colin M.L. Burnett, CC BY-SA 3.0). Do not edit by hand.\n",
        "#include <cstdint>\n\nnamespace chesspieces {\n\n",
        f"constexpr int SIZE = {size};\n",
        f"constexpr int BYTES = {(size * size + 7) // 8};\n\n",
    ]
    preview = Image.new("L", (size * 6, size * 2), 255)
    for idx, name in enumerate(PIECES):
        img = rasterize(os.path.join(svg_dir, name + ".svg"), size)
        shape, ink = masks(img, size)
        parts.append(fmt(f"{name}_shape", shape))
        parts.append(fmt(f"{name}_ink", ink))
        parts.append("\n")
        # Preview on alternating light/dark backgrounds.
        ox, oy = (idx % 6) * size, (idx // 6) * size
        dark = (idx % 2) == 0
        for y in range(size):
            for x in range(size):
                i = y * size + x
                bg = 160 if dark else 255
                v = bg
                if shape[i >> 3] & (0x80 >> (i & 7)):
                    v = 0 if ink[i >> 3] & (0x80 >> (i & 7)) else 255
                preview.putpixel((ox + x, oy + y), v)
    parts.append(
        "// Index: piece type 1..6 (P N B R Q K) per color.\n"
        "constexpr const uint8_t* WHITE_SHAPE[7] = {nullptr, wP_shape, wN_shape, wB_shape, wR_shape, wQ_shape, wK_shape};\n"
        "constexpr const uint8_t* WHITE_INK[7] = {nullptr, wP_ink, wN_ink, wB_ink, wR_ink, wQ_ink, wK_ink};\n"
        "constexpr const uint8_t* BLACK_SHAPE[7] = {nullptr, bP_shape, bN_shape, bB_shape, bR_shape, bQ_shape, bK_shape};\n"
        "constexpr const uint8_t* BLACK_INK[7] = {nullptr, bP_ink, bN_ink, bB_ink, bR_ink, bQ_ink, bK_ink};\n\n"
        "}  // namespace chesspieces\n"
    )
    with open(out, "w") as f:
        f.write("".join(parts))
    preview.resize((size * 6 * 3, size * 2 * 3), Image.NEAREST).save(os.path.join(svg_dir, "preview.png"))


if __name__ == "__main__":
    main()
